# place in and rename roles/dbserver/tasks/main.yml

---
- name: Ensure MariaDB server is installed
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Ensure PyMySQL library is installed
  ansible.builtin.package:
    name: python3-PyMySQL
    state: present

- name: Ensure MariaDB service is enabled
  ansible.builtin.service:
    name: mariadb
    enabled: true

- name: Ensure MariaDB service is started
  ansible.builtin.service:
    name: mariadb
    state: started

# Create database
- name: Create database 'webappdb'
  community.mysql.mysql_db:
    name: webappdb
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root

# Create user
- name: Create database user 'webappuser'
  community.mysql.mysql_user:
    name: webappuser
    password: "{{ webapp_db_password }}"
    priv: "webappdb.*:ALL"
    host: "%"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root