---
- name: Install and configure MariaDB
  hosts: db
  become: true
  vars_files:
    - vault.yml

  tasks:

    - name: Ensure MariaDB server is installed
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Ensure PyMySQL Python library is installed (required for MySQL modules)
      ansible.builtin.package:
        name: python3-PyMySQL
        state: present

    - name: Ensure MariaDB service is enabled and started
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Create database 'webappdb'
      community.mysql.mysql_db:
        name: webappdb
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
        login_user: root

    - name: Create database user 'webappuser' with password and privileges
      community.mysql.mysql_user:
        name: webappuser
        password: "{{ db_password }}"
        priv: "webappdb.*:ALL"
        host: "%"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
        login_user: root